# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef4832dc07a6cac8085b38a6fe6ef890c5dbf135b15a489f92a391670e8f3987f761a2149939d99cd50bb15ac352ca110359972f62fca45177780b14af91e7da

test:
  secret_key_base: 1dfc31dfa1309adaf358b76017e85e38130de9b760e461c7c6f1b4df8b4c49fc13fe0d7f275bc674a2a98c9f2e5c6c409d1079cf92e97da856fb93123f7f2130

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
